#!/bin/sh

install_package() {
    # $@ = packages

    if [ "$APT" = "" ]; then
        echo "This is not an apt system, so cannot install packages. Exiting..."
        exit 1
    fi

    if [ "$(id -u)" -ne 0 ]; then
        DEBIAN_FRONTEND=noninteractive sudo apt update
        DEBIAN_FRONTEND=noninteractive sudo apt install -y $@
    else
        DEBIAN_FRONTEND=noninteractive apt update
        DEBIAN_FRONTEND=noninteractive apt install -y $@
    fi
}

ensure_installed() {
    # $1 = command to check
    # $2 = package name

    if ! command -v $1 &> /dev/null
    then
        echo "$1 could not be found, installing..."
        install_package $2
    fi
}

# Let's do some sanity checks. Make sure $HOME is set
if [ -z "$HOME" ]; then
    echo "HOME is not set. Exiting..."
    exit 1
fi

# Go there
GIT_PARENT_DIR="$HOME"
cd "$GIT_PARENT_DIR"

# Check if we're using apt
APT="$(which apt)"

install_package python3-pip python3-venv git

# Make sure python aliases python3, and create it if it doesn't
if ! command -v python &> /dev/null
then
    echo "Python alias not found. Creating..."
    PY3PATH="$(which python3)"
    PY_ALIAS_PATH="$(echo $PY3PATH | sed 's/.$//' )" # Remove the last character
    ln -s $PY3PATH $PY_ALIAS_PATH 2> /dev/null
fi

# Clone the repos
git clone https://github.com/apaz-cli/Dotfiles &
git clone https://github.com/apaz-cli/Scripts &
#git clone https://github.com/apaz-cli/Secrets --depth=1 &
wait

# Move dotfiles into place.
cp Dotfiles/.bashrc "$HOME/.bashrc"
cp -r Dotfiles/.nano* "$HOME/"

# Install the important packages
install_package "wget curl nano tree locate jq kitty-terminfo"

if [ ! "$PRIME" = "" ]; then
    curl -sSL https://raw.githubusercontent.com/PrimeIntellect-ai/prime/main/scripts/install/install.sh > /tmp/prime_install.sh
    chmod +x /tmp/prime_install.sh
    DEBIAN_NONINTERACTIVE=1 /tmp/prime_install.sh
    rm /tmp/prime_install.sh
fi

echo -e "\n\e[35mSetup complete.\e[0m\n"
